### ISSUE TITLE
commands are never executed

### ISSUE THREAD

**Issue by Somaxa8** [vendelieu/telegram-bot_template#1]
I downloaded this project and configured my token when I wanted to start it to test my bot with the /start command, the CommandHandler never got executed so I never got a response.
Mention that you do not touch anything on the template except the token.
When I tried using a simple main function with a handleUpdates and an onCommand it worked correctly but for some reason when integrating it with spring it doesn't work.

**Comment by vendelieu** [comment]
If you are looking for spring example you can look in spring branch, or ypu want spring example with manual handling?
